import { useEffect, useRef, useState } from 'react';
import { BrainScene } from './components/BrainScene';
import { FlyScene } from './components/FlyScene';
import { Environment } from './components/Environment';
import { Attribution } from './components/Attribution';
import { asset, loadAtlas, type Atlas } from './lib/atlas';
import { frameAt, parseReplay, type ModelReplay } from './lib/replay';

export function App() {
  const [atlas,setAtlas] = useState<Atlas|null>(null);
  const [error,setError] = useState('');
  const [replay,setReplay] = useState<ModelReplay|null>(null);
  const [playing,setPlaying] = useState(true), [time,setTime] = useState(0);
  const file = useRef<HTMLInputElement>(null);
  const duration = replay?.frames.at(-1)?.time ?? 30;
  useEffect(() => {
    const abort = new AbortController();
    void loadAtlas(abort.signal).then(setAtlas).catch(e=>{if(!abort.signal.aborted)setError(String(e));});
    return () => abort.abort();
  },[]);
  useEffect(() => {
    if(!playing) return;
    let previous = performance.now(), frame = 0;
    const step = (now:number) => {
      const delta = document.hidden ? 0 : Math.min(.1,(now-previous)/1000); previous=now;
      setTime(value => Math.min(duration,value+delta));
      frame=requestAnimationFrame(step);
    };
    frame=requestAnimationFrame(step);
    return () => cancelAnimationFrame(frame);
  },[playing,duration]);
  useEffect(()=>{if(time>=duration)setPlaying(false);},[time,duration]);
  const accept = (value:unknown) => {
    if(!atlas) throw Error('Wait for the atlas to load.');
    const validated = parseReplay(value,atlas.visibleIds);
    setReplay(validated);setTime(0);setPlaying(false);setError('');
  };
  const example = async () => {
    try {const response=await fetch(asset('examples/model-output.example.json'));if(!response.ok)throw Error('Example unavailable.');accept(await response.json());}
    catch(e){setError(String(e));}
  };
  const frame = replay ? frameAt(replay,time) : null;
  return <>
    <header><h1>YOUR EXPERIMENT</h1><span>Environment / anatomy / model output</span><a href="https://github.com/cobanov/fly-connectome-template#readme">Template guide ↗</a></header>
    <main>
      <div className="toolbar">
        <span className="status">{playing?'Running':'Paused'} · {time.toFixed(2)} s</span>
        <div className="controls">
          <button onClick={()=>{setTime(0);setPlaying(false);}}>Reset</button>
          <button onClick={()=>{if(time>=duration)setTime(0);setPlaying(!playing);}}>{playing?'Pause':'Play'}</button>
          <button disabled={!atlas} onClick={()=>void example()}>Load synthetic example</button>
          <button disabled={!atlas} onClick={()=>file.current?.click()}>Load model JSON</button>
          {replay&&<button onClick={()=>{setReplay(null);setTime(0);setPlaying(false);}}>Clear output</button>}
          <input ref={file} hidden type="file" accept=".json,application/json" onChange={async event=>{
            const selected=event.target.files?.[0];event.target.value='';if(!selected)return;
            try {if(selected.size>10*1024*1024)throw Error('Replay must be under 10 MB.');accept(JSON.parse(await selected.text()));} catch(e){setError(String(e));}
          }}/>
        </div>
      </div>
      {error&&<p className="error" role="alert">{error}</p>}
      <div className="workbench">
        <section className="panel environment-panel"><h2>01 / ENVIRONMENT</h2><Environment time={time}/><div className="panel-bottom">Generic stimulus · no game or reward function bundled</div></section>
        <section className="panel brain-panel"><h2>02 / BRAIN SOMA ATLAS <span>MaleCNS v1.0</span></h2>
          {atlas?<BrainScene atlas={atlas} frame={frame}/>:<p className="loading" role="status">Loading measured anatomy…</p>}
          <div className="panel-bottom">{atlas?.visibleIds.size.toLocaleString('en-US') ?? '…'} measured somata <a href={asset('data/brain-atlas/NOTICE.md')}>Data notice ↗</a></div>
        </section>
        <section className="panel fly-panel"><h2>03 / BODY <span>Flybody</span></h2><FlyScene/><div className="panel-bottom">Anatomical mesh · no motor simulation <span>Drag to rotate</span></div></section>
      </div>
      <section className="model-status" aria-label="Model provenance">
        <strong>{replay ? `${replay.source.kind.toUpperCase()} OUTPUT` : 'ANATOMY ONLY'}</strong>
        <p>{replay ? replay.source.name : 'No neural model connected. No activity is generated by default.'}</p>
        {replay&&<><p>Normalization: {replay.source.normalization}</p><p>{replay.source.kind==='synthetic'?'Demonstration values only; not neural activity and not driven by the stimulus.':'Source category is declared by the uploaded file, not independently verified by this viewer.'}</p></>}
        <label>Experiment time <input type="range" aria-label="Experiment time" min="0" max={duration} step=".01" value={time} onChange={event=>setTime(Number(event.target.value))}/><span>{duration.toFixed(1)} s</span></label>
      </section>
      <details><summary>Scientific scope &amp; customization</summary><p>The atlas contains curated cell-body positions, not neurite morphology or synaptic edges. Points keep native proportions. Missing soma locations are never generated. The brain filter selects optic, central and descending classes; it is not a complete brain segmentation.</p><p>Replace Environment.tsx with your environment. Pass ActivityFrame values to BrainScene using MaleCNS body IDs and time in seconds. The JSON loader validates the dataset, visible IDs and normalized values. GPU training and model inference run separately.</p><p>Dataset creators: FlyEM / HHMI Janelia, University of Cambridge, MRC Laboratory of Molecular Biology and Google Research. <a href="https://male-cns.janelia.org/download/">MaleCNS data and publication</a>, CC BY 4.0. <a href={asset('data/brain-atlas/manifest.json')}>Exact source, filters and hashes</a>.</p><p>Template code has a custom attribution-required license. Keep the linked template/author credit in your web UI and repository README. Third-party assets retain their own licenses.</p></details>
    </main>
    <Attribution/>
  </>;
}
